-- == MAGNITUDE == --

-- TOTAL CUSTOMERS BY COUNTRY
SELECT
    Country,
    COUNT(customer_key) Tot_customer_by_country
FROM gold.dim_customers
GROUP BY country
ORDER BY Tot_customer_by_country DESC;


-- TOTAL CUSTOMERS BY GENDER
SELECT
    gender,
    COUNT(customer_key) Tot_customers_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY Tot_customers_by_gender DESC;


-- TOTAL PRODUCTS BY CATEGORY
SELECT
    Category,
    COUNT(product_key) Tot_products
FROM gold.dim_products
GROUP BY category
ORDER BY Tot_products DESC;


-- AVG COST IN EACH CATEGORY
SELECT
    Category,
    COUNT(product_key) Tot_products,
    AVG(cost) Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Tot_products DESC;


-- TOTAL REVENUE BY EACH CATEGORY
SELECT
    P.Category,
    SUM(S.sales_amount) Tot_revenue
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_products AS P
    ON S.product_key = P.product_key
GROUP BY P.Category
ORDER BY Tot_revenue DESC;


-- TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT
    C.customer_key,
    C.first_name,
    C.last_name,
    SUM(F.sales_amount) Tot_revenue
FROM gold.fact_sales AS F
LEFT JOIN gold.dim_customers AS C
    ON F.customer_key = C.customer_key
GROUP BY
    C.customer_key,
    C.first_name,
    C.last_name
ORDER BY Tot_revenue DESC;


-- Distribution of items across country (total quantity)
SELECT
    C.Country,
    SUM(F.quantity) Tot_quantity
FROM gold.fact_sales AS F
LEFT JOIN gold.dim_customers AS C
    ON F.customer_key = C.customer_key
GROUP BY C.country
ORDER BY Tot_quantity DESC;